#!/bin/sh
#
# tools/wrapper
#
# Copyright (C) 2016 James Hogan <james@albanarts.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details
# (in the file called COPYING).
#
#
# Wraps a prolog script to make its interface a little cleaner.
#

ABSPATH=$(cd "$(dirname "$0")"; pwd)
exec swipl -q -p "chron=$ABSPATH/../src" -s "${0}.pl" -- "$@"
